services:
  catalogdb:
    image: postgres:latest

  basketdb:
   image: postgres:latest

  distributedcache:
    image: redis:latest

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  eshopping.catalog.api:
    image: ${DOCKER_REGISTRY-}eshoppingcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShopping.Catalog.Api/Dockerfile

  eshopping.basket.api:
    image: ${DOCKER_REGISTRY-}eshoppingbasketapi
    build:
      context: .
      dockerfile: Services/Basket/EShopping.Basket.Api/Dockerfile

  eshopping.discount.grpc:
    image: ${DOCKER_REGISTRY-}eshoppingdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/EShopping.Discount.Grpc/Dockerfile

  eshopping.ordering.api:
    image: ${DOCKER_REGISTRY-}eshoppingorderingapi
    build:
      context: .
      dockerfile: Services/Ordering/EShopping.Ordering.Api/Dockerfile

  eshopping.yarpapigateway:
    image: ${DOCKER_REGISTRY-}eshoppingyarpapigateway
    build:
      context: .
      dockerfile: ApiGatetways/EShopping.YarpApiGateway/Dockerfile

  eshopping.web:
    image: ${DOCKER_REGISTRY-}eshoppingweb
    build:
      context: .
      dockerfile: WebApps/EShopping.Web/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

networks:
  eshopping:


