 services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    networks:
      - eshopping

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDB
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
    networks:
      - eshopping

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - eshopping

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc12345678
    restart: always
    ports:
      - "1433:1433"
    networks:
      - eshopping

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QAi0PGiy2pfg4UcZtBv+OgfXYVCLASIY+m/NrgklPbzAbxaaqKFbieyvxadEiHRlHlQ2LiXGTqVC+OcTF8ifQ75U50HMUF98m9VEgYlhgozw #Abc123
    ports:
      - "6969:80"
      - "5341:5341"
    volumes:
      - "C:\\ContainerData\\Seq\\data:/data"
    networks:
      - eshopping

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - eshopping

  eshopping.catalog.api:
    container_name: eshopping.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__CatalogDb=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microservice.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc123
      - Seq__Url=http://seq:5341
    depends_on:
      - catalogdb
      - seq
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./https:/https:ro
    networks:
      - eshopping

  eshopping.basket.api:
    container_name: eshopping.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__BasketDB=Server=basketdb;Port=5432;Database=BasketDB;User Id=postgres;Password=postgres;Include Error Detail=true 
      - ConnectionStrings__Redis=distributedcache:6379
      - ConnectionStrings__Discount=http://eshopping.discount.grpc:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microservice.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc123
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Seq__Url=http://seq:5341
    depends_on:
      - basketdb
      - distributedcache
      - eshopping.discount.grpc
      - messagebroker
      - seq
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./https:/https:ro
    networks:
      - eshopping

  eshopping.discount.grpc:
    container_name: eshopping.discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DiscountDB=Data Source=discountdb.db
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microservice.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc123
      - Seq__Url=http://seq:5341
    depends_on:
      - seq
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./https:/https:ro
    networks:
      - eshopping

  eshopping.ordering.api:
    container_name: eshopping.ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=Abc12345678;Encrypt=False;TrustServerCertificate=True 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microservice.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc123
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Seq__Url=http://seq:5341
    depends_on:
      - orderdb
      - messagebroker
      - seq
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./https:/https:ro
    networks:
      - eshopping

  eshopping.yarpapigateway:
    container_name: eshopping.yarpapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microservice.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc123
      - Seq__Url=http://seq:5341
    depends_on:
      - seq
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./https:/https:ro
    networks:
      - eshopping

  eshopping.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/microservice.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc123
      - ApiSettings__GatewayAddress=http://eshopping.yarpapigateway:8080
    ports:
      - "6005:8080"
      - "6065:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./https:/https:ro
    networks:
      - eshopping
