services:
  catalogdb:
    image: postgres:latest

  basketdb:
   image: postgres:latest

  distributedcache:
    image: redis:latest

  eshopping.catalog.api:
    image: ${DOCKER_REGISTRY-}eshoppingcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShopping.Catalog.Api/Dockerfile

  eshopping.basket.api:
    image: ${DOCKER_REGISTRY-}eshoppingbasketapi
    build:
      context: .
      dockerfile: Services/Basket/EShopping.Basket.Api/Dockerfile

  eshopping.discount.grpc:
    image: ${DOCKER_REGISTRY-}eshoppingdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/EShopping.Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

networks:
  eshopping: